### ISSUE TITLE
The title bar is the windows theme & Border is not rounded(maybe you are using windows11?).

### ISSUE THREAD

**Issue by zhiyu1998** [dy-sh/one-dark-potplayer-theme#1]
It's an honor to use the theme you made. Nice and look at that so delicate.
But I encountered some problems during use. As the title says. If you have time to solve this problem, I will thank you very much.
[details](https://postimg.cc/9zcFnrGn)

**Comment by dy-sh** [comment]
I have rounded edges. I'm using windows 11. I also advise you to read the updated readme to fix the color of the window title bar.

**Comment by zhiyu1998** [comment]
@dy-sh thx!!
